[package]
name = "rust-template"
version = "0.1.0"
authors = ["DenTaku <dentaku1412@gmail.com>"]
edition = "2021"
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
